version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blackhole-logger
    hostname: blackhole-logger
    restart: unless-stopped
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    volumes:
      - .:/app
    ports:
      - 9999:5000

